<?php

/**
 * AUTOGENERATED FILE WILL BE OVERWRITTEN ON EACH
 * composer horde-reconfigure or install/update
 * Override settings in either:
 * - var/config/horde/registry.local.php
 * - var/config/horde/registry.d/ snippets, i.e. 99-custom.php
 * - var/config/horde/registry-sub.domain.org.php
 */
$this->applications['jonah']['fileroot'] = '/home/i567442/php/git/horde/jonah/vendor/horde/jonah/';
$this->applications['jonah']['templates'] = '/home/i567442/php/git/horde/jonah/vendor/horde/jonah/templates/';
$this->applications['jonah']['themesfs'] = '/home/i567442/php/git/horde/jonah/web/themes/jonah/';
$this->applications['jonah']['jsfs'] = '/home/i567442/php/git/horde/jonah/web/js/jonah/';
$this->applications['jonah']['webroot'] = '/jonah/';
$this->applications['jonah']['jsuri'] = '/js/jonah';
$this->applications['jonah']['themesuri'] = '/themes/jonah';
// End of jonah registry snippet
