<?php

/**
 * AUTOGENERATED ONLY IF ABSENT
 * If you activate at least one of these lines, please also set a full https URL for the default webroot where the remaining apps and the assets (js, themes, static) are located
 * Run `composer horde:reconfigure --mode=proxy --webroot="https://assets.example.com/"`
 */
// Customize horde/horde webroot
// $this->applications['horde']['webroot'] = 'https://horde.example.com/';
// Customize horde/jonah webroot
// $this->applications['jonah']['webroot'] = 'https://jonah.example.com/';
