<?php

/**
 * Jonah route definitions.
 *
 * ADMINISTRATORS: Do not edit this file. Put custom routes into
 * var/config/jonah/routes.local.php and run composer horde:reconfigure
 *
 * Copyright 2008-2026 Horde LLC (http://www.horde.org/)
 *
 * See the enclosed file LICENSE for license information (BSD). If you did
 * not receive this file, see http://cvs.horde.org/co.php/jonah/LICENSE.
 */

namespace Horde\Jonah;

use Horde\Core\Middleware\DefaultStack;
use Horde\Jonah\Controller\Channel;
use Horde\Jonah\Controller\Story;
use Horde\Jonah\Controller\Feed;
use Horde\Jonah\Controller\TagSearchController;

// --- Channel management ---

$mapper->buildRoute(uri: '/channels', name: 'ChannelList')
    ->withController(Channel\ListController::class)
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/channels/index.php')
    ->add();

$mapper->buildRoute(uri: '/channels/edit', name: 'ChannelCreate')
    ->withController(Channel\EditController::class)
    ->withDefaults(['action' => 'create'])
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/channels/edit.php')
    ->add();

$mapper->buildRoute(uri: '/channels/edit/:channel_id', name: 'ChannelEdit')
    ->withController(Channel\EditController::class)
    ->withDefaults(['action' => 'edit'])
    ->withRequirements(['channel_id' => '\d+'])
    ->withMiddleware(DefaultStack::get())
    ->add();

$mapper->buildRoute(uri: '/channels/delete/:channel_id', name: 'ChannelDelete')
    ->withController(Channel\DeleteController::class)
    ->withRequirements(['channel_id' => '\d+'])
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/channels/delete.php')
    ->add();

// --- Story management ---

$mapper->buildRoute(uri: '/stories', name: 'StoryListDefault')
    ->withController(Story\ListController::class)
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/stories/index.php')
    ->add();

$mapper->buildRoute(uri: '/stories/:channel_id', name: 'StoryList')
    ->withController(Story\ListController::class)
    ->withRequirements(['channel_id' => '\d+'])
    ->withMiddleware(DefaultStack::get())
    ->add();

$mapper->buildRoute(uri: '/stories/view/:channel_id/:id', name: 'StoryView')
    ->withController(Story\ViewController::class)
    ->withRequirements(['channel_id' => '\d+', 'id' => '\d+'])
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/stories/view.php')
    ->add();

$mapper->buildRoute(uri: '/stories/edit/:channel_id', name: 'StoryCreate')
    ->withController(Story\EditController::class)
    ->withDefaults(['action' => 'create'])
    ->withRequirements(['channel_id' => '\d+'])
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/stories/edit.php')
    ->add();

$mapper->buildRoute(uri: '/stories/edit/:channel_id/:id', name: 'StoryEdit')
    ->withController(Story\EditController::class)
    ->withDefaults(['action' => 'edit'])
    ->withRequirements(['channel_id' => '\d+', 'id' => '\d+'])
    ->withMiddleware(DefaultStack::get())
    ->add();

$mapper->buildRoute(uri: '/stories/delete/:channel_id/:id', name: 'StoryDelete')
    ->withController(Story\DeleteController::class)
    ->withRequirements(['channel_id' => '\d+', 'id' => '\d+'])
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/stories/delete.php')
    ->add();

$mapper->buildRoute(uri: '/stories/share/:channel_id/:id', name: 'StoryShare')
    ->withController(Story\ShareController::class)
    ->withRequirements(['channel_id' => '\d+', 'id' => '\d+'])
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/stories/share.php')
    ->add();

$mapper->buildRoute(uri: '/stories/pdf/:channel_id/:id', name: 'StoryPdf')
    ->withController(Story\PdfController::class)
    ->withRequirements(['channel_id' => '\d+', 'id' => '\d+'])
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/stories/pdf.php')
    ->add();

// --- Feed delivery ---

$mapper->buildRoute(uri: '/feeds/:feed', name: 'FeedHtml')
    ->withController(Feed\HtmlController::class)
    ->withDefaults(['filter' => '', 'value' => ''])
    ->withMiddleware(DefaultStack::get())
    ->add();

$mapper->buildRoute(uri: '/feeds/:feed/:filter/:value', name: 'FeedFiltered')
    ->withController(Feed\HtmlController::class)
    ->withMiddleware(DefaultStack::get())
    ->add();

$mapper->buildRoute(uri: '/rss/:channel_id', name: 'FeedRss')
    ->withController(Feed\RssController::class)
    ->withRequirements(['channel_id' => '\d+'])
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/delivery/rss.php')
    ->add();

// --- Tag search ---

$mapper->buildRoute(uri: '/search/tags', name: 'TagSearch')
    ->withController(TagSearchController::class)
    ->withMiddleware(DefaultStack::get())
    ->withSecondaryRoute('/stories/results.php')
    ->add();
