<?php
/**
 * This file stores the templates used to generate different views of
 * news channels.
 *
 * IMPORTANT: DO NOT EDIT THIS FILE!
 * Local overrides MUST be placed in var/config/jonah/templates.local.php or
 * var/config/jonah/templates.d/.
 * If the 'vhosts' setting has been enabled in Horde's configuration, you can
 * use var/config/jonah/templates-servername.php.
 */

$templates['standard'] = array(
    'name' => _("Standard"),
    'view_template' => 'standard',
);

$templates['media'] = array(
    'name' => _("Media"),
    'view_template' => 'media',
);

$templates['internal'] = array(
    'name' => _("Internal"),
    'view_template' => 'internal',
);

$templates['compact'] = array(
    'name' => _("Compact"),
    'view_template' => 'compact',
);

$templates['ultracompact'] = array(
    'name' => _("Ultracompact"),
    'view_template' => 'ultracompact',
);
